laboref/applications/animal/urls.py
from django.urls import path

from .views import IndexView, detail_animal_view, edit_animal_view, new_animal_view

animal_patterns = ([
	path('', IndexView.as_view(), name='index'),
	path('<int:animal_id>/', detail_animal_view, name="detail_animal"),
	path('edit/<int:animal_id>/', edit_animal_view, name="edit_animal"),
	path('new/', new_animal_view, name="new_animal"),
], 'animal')

laboref/laboref/urls.py
from django.contrib import admin
from django.urls import path, include
from applications.animal.urls import animal_patterns
from applications.core.urls import core_patterns
from applications.adoptions.urls import adoptions_patterns
from applications.blog.urls import blog_patterns
from applications.contacts.urls import contacts_patterns
from applications.about.urls import about_patterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_patterns)),
    path('animal/', include(animal_patterns)),
    path('adoptions/', include(adoptions_patterns)),
    path('blog/', include(blog_patterns)),
    path('contacts/', include(contacts_patterns)),
    path('about/', include(about_patterns)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laboref/applications/animal/models.py
from django.db import models


# tipo de animal

class AnimalType(models.Model):
    animal_type_name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Tipo de animal"
        verbose_name_plural = "Tipos de animales"

    def __str__(self):
        return self.animal_type_name


# raza

class Breed(models.Model):
    animal_type = models.ForeignKey(AnimalType, on_delete=models.CASCADE)
    breed_name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Raza de animal"
        verbose_name_plural = "Razas"

    def __str__(self):
        return self.breed_name


# color del animal

class AnimalColor(models.Model):
    color_name = models.CharField(max_length=255)

    class Meta:
        verbose_name = "Color de animal"
        verbose_name_plural = "Color de animales"

    def __str__(self):
        return self.color_name


# animal
class Animal(models.Model):
    animal_name = models.CharField(max_length=255)
    animal_breed = models.ForeignKey(Breed, on_delete=models.DO_NOTHING)
    animal_color = models.ForeignKey(AnimalColor, on_delete=models.DO_NOTHING)
    animal_age = models.IntegerField()
    animal_image = models.ImageField(upload_to='animal/', default='media/None/no-img.jpg')
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name_plural = "Animales"
        ordering = ['created']

    def __str__(self):
        return self.animal_name


# animals images
class AnimalImage(models.Model):
    image_description = models.TextField()
    image_url = models.ImageField(upload_to='animal/', default='media/None/no-img.jpg')
    image_animal = models.ForeignKey(Animal, on_delete=models.CASCADE)

laboref/applications/animal/forms.py
from django import forms

from .models import Animal


class EditAnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ('animal_name', "animal_age", "animal_breed", "animal_color")


class NewAnimalForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = ('' 'animal_name', "animal_age", "animal_breed", "animal_color")

laboref/applications/animal/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .forms import EditAnimalForm, NewAnimalForm
from .models import Animal


class IndexView(ListView):
    template_name = "animal/index.html"
    model = Animal


def detail_animal_view(request, animal_id):
    animal = get_object_or_404(Animal, pk=animal_id)
    return render(request, "animal/detail.html", {'animal': animal})


def edit_animal_view(request, animal_id):
    animal = Animal.objects.get(id=animal_id)
    form = EditAnimalForm(initial={
        'animal_name': animal.animal_name,
        'animal_breed': animal.animal_breed,
        'animal_color': animal.animal_color,
        'animal_age': animal.animal_age
    })
    context = {'form': form, 'animal': animal}
    return render(request, "animal/edit.html", context)


def new_animal_view(request):
    if request.method == "POST":
        form = NewAnimalForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('index')
    else:
        form = NewAnimalForm()
    return render(request, "animal/edit.html", {'form': form})

laboref/applications/animal/templates/animal/detail.html
{%extends 'core/base.html'%}

{% block title %}{{ animal.animal_name }}{% endblock %}

{% block content %}
{% load static %}

<div class="content-detail">

   <div style="width: 30%; position: relative;" >
      <img class="image_pet_detail" src="{{ animal.animal_image.url }}" />
   </div>

  <div style="width: 60%">
      <h1 class="h_modified"> {{ animal.animal_name }} </h1><br>
      <b> Raza: </b> {{ animal.animal_breed }} <br>
      <b> Color: </b>{{ animal.animal_color }} <br>
      <b> Edad (años): </b> {{ animal.animal_age }}<br>
     <a class="btn btn-laboref " > Adoptar </a>
  </div>

   <!--
   <td> <a class=btn href="/animal/edit/{{animal.id}}"> <i class="icon-pencil"></i> Editar </a> </td>

   {%if user.is_authenticated %}
      <td> <a class=btn href="/edit/animal/{{animal.id}}"> <i class="icon-pencil"></i> Editar </a> </td>
   {% endif %}
   -->
</div>
{% endblock %}

{% block tips_more %}
<hr> {% endblock %}

laboref/applications/animal/templates/animal/edit.html
{%extends 'core/base.html'%}

{% block content %}
<div class="row">
    <div class="span6">
        <form action="" method="post" class="post-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Guardar Cambios">
        </form>
    </div>
    <div class="span6">
        <img src="/{{animal.animal_image}}">
    </div>
</div>
<!--
 {%if user.is_authenticated %}
    <td> <a class=btn href="/edit/animal/{{animal.id}}"> <i class="icon-pencil"></i> Editar </a> </td>
 {% endif %}
 -->

{% endblock %}

laboref/applications/animal/templates/animal/index.html
{%extends 'core/base.html'%}

{% block content %}

{% if animal_list %}
<ul>
    {% for animal in animal_list %}
    <li> <a href="/animal/{{ animal.id }}/">{{ animal.animal_name }} </a> </li>
    {% endfor %}
</ul>

<li> <a class="btn btn-success" href="/animal/new/">Nuevo Registro </a> </li>


{% else %}

<p>No animal are available.</p>

{% endif %}

{% endblock%}